---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: bz_repro
    apps.open-cluster-management.io/github-path: rdr/app-busybox-5/busybox
  labels:
    app: busybox-sample
  name: busybox-sub
spec:
    channel: ramen-busybox-5/ramen-gitops
    placement:
      placementRef:
        kind: PlacementRule
        name: busybox-placement
