apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: busybox
  name: dd-io-pvc-5
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 115Gi
  storageClassName: ocs-storagecluster-ceph-rbd-mirror
