apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: busybox
  name: dd-io-pvc-4
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 106Gi
  storageClassName: ocs-storagecluster-ceph-rbd-mirror
