apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: busybox-cephfs
  name: dd-io-pvc-6
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 129Gi
  storageClassName: ocs-storagecluster-cephfs
