apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: busybox
  name: dd-io-pvc-5
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 115Gi
  storageClassName: ocs-storagecluster-cephfs
