apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appname: dd-io-2
  name: dd-io-2
spec:
  selector:
    matchLabels:
      workload: dd-io-2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        workload: dd-io-2
    spec:
      containers:
      - command:
        - sh
        - -c
        - /run-io.sh
        image: quay.io/prsurve/busybox:test
        imagePullPolicy: Always
        name: busybox
        env:
        - name: NAMESPACE_WA
          value: "busybox-workloads-8"
        volumeMounts:
        - mountPath: /mnt/test
          name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: dd-io-pvc-2
          readOnly: false
