apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appname: dd-io-4
  name: dd-io-4
spec:
  selector:
    matchLabels:
      workload: dd-io-4
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        workload: dd-io-4
    spec:
      containers:
      - command:
        - sh
        - -c
        - /run-io.sh
        image: quay.io/prsurve/busybox:latest
        imagePullPolicy: Always
        name: busybox
        env:
        - name: NAMESPACE_WA
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /mnt/test
          name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: dd-io-pvc-4
          readOnly: false
