---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: multi-busybox-drpc-1
  labels:
    app: multi-busybox-sample
spec:
  preferredCluster: "vmware-dccp-one"
  drPolicyRef:
    name: odr-policy-east-west-rpo-5m
  placementRef:
    kind: PlacementRule
    name: busybox-placement-1
  pvcSelector:
    matchLabels:
      appname: busybox
