apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: busybox
  name: dd-io-pvc-7
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 149Gi
  storageClassName: ocs-storagecluster-ceph-rbd
