apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: busybox
  name: busybox-pvc-10
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 87Gi
  storageClassName: ocs-storagecluster-cephfs
